name: "Video Updater"
on:
  schedule:
  - cron: "*/6 * * * *"
  
jobs:
  video_updater_job:
    runs-on: ubuntu-latest
    name: A job to update video
    steps:
      - name: WhoozyAction
        id: videoUpdater
        uses: saifulriza/whoozy@v1.7
        with:
          apiKey: ${{ secrets.ENV_API_KEY }}
          videoId: ${{ secrets.ENV_VIDEO_ID }}
          videoTitle: 'Internet of Thing | WATCH {watch} | LIKE {like} | DISLIKE {dislike} | COMMENT {comment} | SUBSCRIBE {subscribe}'
          channelId: ${{ secrets.ENV_CHANNEL_ID }}
          refreshToken: ${{ secrets.ENV_REFRESH_TOKEN }}
          clientSecret: ${{ secrets.ENV_CLIENT_SECRET }}
          redirectUri: ${{ secrets.ENV_REDIRECT_URI }}
          clientId: ${{ secrets.ENV_CLIENT_ID }}
